CREATE VIEW EMP_FULL AS
	SELECT E.*, D.DEPARTMENT_NAME, L.CITY, C.COUNTRY_NAME, R.REGION_NAME
	FROM EMPLOYEES E
	INNER JOIN DEPARTMENTS D
	ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
	INNER JOIN LOCATIONS L
	ON D.LOCATION_ID = L.LOCATION_ID
	INNER JOIN COUNTRIES C
	ON L.COUNTRY_ID = C.COUNTRY_ID
	INNER JOIN REGIONS R
	ON C.REGION_ID = R.REGION_ID;


SELECT * FROM EMP_FULL
WHERE COUNTRY_NAME = 'United States of America';

--CREAR SECUENCIA
CREATE SEQUENCE SEQ01 START WITH 120;
CREATE SEQUENCE SEQ02 START WITH 10 INCREMENT BY 5;

--OBTENER EL SIGUIENTE VALOR DE LA SECUENCIA
SELECT nextval('SEQ01');
SELECT nextval('SEQ02');

--OBTENER EL VALOR ACTUAL DE LA SECUENCIA
SELECT currval('SEQ01');
SELECT currval('SEQ02');

--CREACION DE TABLA CON CAMPO SERIAL
CREATE TABLE CATEGORY(
	ID SERIAL PRIMARY KEY,
	DESCRIPTION TEXT
);

--INSERCION
INSERT INTO CATEGORY(DESCRIPTION) VALUES('Electronics');
INSERT INTO CATEGORY(DESCRIPTION) VALUES('Home');

--SECUENCIA CREADA
SELECT currval('CATEGORY_ID_SEQ');


--INDICES
--*******

--VERIFICAR LOS INDICES DE UNA TABLA
SELECT * FROM PG_INDEXES
WHERE TABLENAME = 'departments';


--CREACION DE TABLA DE PRUEBA
CREATE TABLE TEST_TABLE(
	VALUE1 NUMERIC,
	VALUE2 NUMERIC
);

--PARA LAS PRUEBAS INSERTAREMOS 500,000 DATOS
DO $$
BEGIN
	FOR i IN 1..500000 LOOP
		--GENERAMOS NUMEROS ALEATORIOS
		INSERT INTO TEST_TABLE VALUES(trunc(random() * 100000000), trunc(random() * 100000000));
	END LOOP;	
END;
$$

--CREACION DE INDICE
CREATE INDEX IX_TT_V1 ON TEST_TABLE(VALUE1);

--REVISAMOS EL PLAN DE EJECUCION
EXPLAIN ANALYZE SELECT * FROM TEST_TABLE WHERE VALUE1 BETWEEN 1000 AND 100000;

--SI SE APLICA UNA FUNCION AL VALOR DE DESTINO, EL INDICE NO SE APLICA
EXPLAIN ANALYZE SELECT * FROM TEST_TABLE WHERE TRUNC(VALUE1) BETWEEN 1000 AND 100000;

--CREACION DE INDICE PARA EL SEGUNDO VALOR
CREATE INDEX IX_TT_V2 ON TEST_TABLE(VALUE2);

--REVISAMOS EL PLAN DE EJECUCION PARA UNA CONSULTA CON EL SEGUNDO VALOR
EXPLAIN ANALYZE SELECT * FROM TEST_TABLE WHERE VALUE2 BETWEEN 1000 AND 100000;

--PODEMOS REALIZAR LA BUSQUEDA CON AMBOS CAMPOS
EXPLAIN ANALYZE 
SELECT * FROM TEST_TABLE
WHERE VALUE1 BETWEEN 1000 AND 100000
AND VALUE2 BETWEEN 500 AND 60000;

--ELIMINACION DE INDICES
DROP INDEX IX_TT_V2;
DROP INDEX IX_TT_V2;

--CREACION DE INDICE PARA AMBOS CAMPOS
CREATE INDEX IX_TT_V1V2 ON TEST_TABLE(VALUE1, VALUE2);

--1) SI FILTRAMOS POR VALUE2, NO TOMA EN CUENTA EL INDICE
EXPLAIN ANALYZE SELECT * FROM TEST_TABLE WHERE VALUE2 BETWEEN 1000 AND 100000;

--2) SI FILTRAMOS POR VALUE1, TOMA EN CUENTA EL INDICE
EXPLAIN ANALYZE SELECT * FROM TEST_TABLE WHERE VALUE1 BETWEEN 1000 AND 100000;


--USUARIOS
--*********

--CREACION DE USUARIOS
CREATE USER USER01 WITH ENCRYPTED PASSWORD 'mypassword';
CREATE USER USER02 WITH ENCRYPTED PASSWORD 'mypassword' CONNECTION LIMIT 2 VALID UNTIL '2022-08-01';

--CREACION DE ROLES
CREATE ROLE ANALYST;

--ASIGNAR PERMISOS - ASIGNAR ROLES
ALTER ROLE ANALYST LOGIN CREATEDB CREATEROLE;

--ASIGNAR A "USER01" EL ROL ANALYST
GRANT ANALYST TO USER01;

--DAR PRIVILEGIOS DE SELECCION SOBRE LA TABLA EMPLOYEES A USERO01
GRANT SELECT ON EMPLOYEES TO USER01;

--DAR PRIVILEGIOS DE SELECCION, ACTUALIZACION Y ELIMINACION SOBRE LA TABLA EMPLOYEES A USER02
GRANT SELECT, UPDATE, DELETE ON EMPLOYEES TO USER02;

--DAR TODOS LOS PRIVILEGIOS SOBRE LA TABLA DEPARTMENTS A USER01
GRANT ALL ON DEPARTMENTS TO USER01;  

--DAR PRIVILEGIO DE LECTURA EN LA TABLA COUNTRIES A TODOS LOS USUARIOS
GRANT SELECT ON COUNTRIES TO PUBLIC;






SELECT * FROM EMPLOYEES E
                 INNER JOIN DEPARTMENTS D
                 ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
                 WHERE EMPLOYEE_ID = 101



CREATE TABLE projects (
	"id" numeric(7) NOT NULL,
	"name" varchar(30) NOT NULL,
	"description" text NULL,
	"createdAt" date NULL,
	"updatedAt" date NULL,
	CONSTRAINT projects_pkey PRIMARY KEY (id)
);


INSERT INTO public.projects
VALUES(1, 'Backend project', 'HR app with Node.js and Express', CURRENT_DATE, CURRENT_DATE);
INSERT INTO public.projects
VALUES(2, 'Frontend project', 'HR app with React', CURRENT_DATE, CURRENT_DATE);
INSERT INTO public.projects
VALUES(3, 'Fullstack project', 'Many tools', CURRENT_DATE, CURRENT_DATE);























