--FUNCIONES - CADENAS
SELECT UPPER(FIRST_NAME), LOWER(LAST_NAME), INITCAP('prueba initcap')
FROM EMPLOYEES;

SELECT 	FIRST_NAME, SUBSTR(FIRST_NAME, 2, 4), LENGTH(FIRST_NAME),
		POSITION('al' IN FIRST_NAME),
		RPAD(FIRST_NAME, 20, '*'),
		LPAD(CAST(EMPLOYEE_ID AS VARCHAR), 10, '0')
FROM EMPLOYEES;

--FUNCIONES - VALORES NUMERICOS
SELECT ROUND(12.4);
SELECT ROUND(12.6);
SELECT ROUND(14.84857, 2);
SELECT ROUND(47, -1);
SELECT ROUND(88, -2);


SELECT TRUNC(12.4);
SELECT TRUNC(12.6);
SELECT TRUNC(14.84857, 2);
SELECT TRUNC(AVG(SALARY), 2) FROM EMPLOYEES;

--FUNCIONES DE FECHA
SELECT CURRENT_DATE - TO_DATE('10/01/2021', 'DD/MM/YYYY');
SELECT CURRENT_DATE, CURRENT_TIMESTAMP, CURRENT_TIME;
SELECT TO_TIMESTAMP('10/01/2021 10:05:30', 'DD/MM/YYYY hh24:mi:ss');
SELECT TO_CHAR(CURRENT_DATE, 'DD-MM-YYYY');

SELECT 	HIRE_DATE, EXTRACT(YEAR FROM HIRE_DATE), EXTRACT(MONTH FROM HIRE_DATE),
		DATE_TRUNC('MONTH', HIRE_DATE), DATE_TRUNC('YEAR', HIRE_DATE),
		AGE(CURRENT_DATE, HIRE_DATE)
FROM EMPLOYEES;