--FUNCIONES - CADENAS
SELECT UPPER(FIRST_NAME), LOWER(LAST_NAME), INITCAP('prueba initcap')
FROM EMPLOYEES;

SELECT 	FIRST_NAME, SUBSTR(FIRST_NAME, 2, 4), LENGTH(FIRST_NAME),
		POSITION('al' IN FIRST_NAME),
		RPAD(FIRST_NAME, 20, '*'),
		LPAD(CAST(EMPLOYEE_ID AS VARCHAR), 10, '0')
FROM EMPLOYEES;

--FUNCIONES - VALORES NUMERICOS
SELECT ROUND(12.4);
SELECT ROUND(12.6);
SELECT ROUND(14.84857, 2);
SELECT ROUND(47, -1);
SELECT ROUND(88, -2);


SELECT TRUNC(12.4);
SELECT TRUNC(12.6);
SELECT TRUNC(14.84857, 2);
SELECT TRUNC(AVG(SALARY), 2) FROM EMPLOYEES;

--FUNCIONES DE FECHA
SELECT CURRENT_DATE - TO_DATE('10/01/2021', 'DD/MM/YYYY');
SELECT CURRENT_DATE, CURRENT_TIMESTAMP, CURRENT_TIME;
SELECT TO_TIMESTAMP('10/01/2021 10:05:30', 'DD/MM/YYYY hh24:mi:ss');
SELECT TO_CHAR(CURRENT_DATE, 'DD-MM-YYYY');

SELECT 	HIRE_DATE, EXTRACT(YEAR FROM HIRE_DATE), EXTRACT(MONTH FROM HIRE_DATE),
		DATE_TRUNC('MONTH', HIRE_DATE), DATE_TRUNC('YEAR', HIRE_DATE),
		AGE(CURRENT_DATE, HIRE_DATE)
FROM EMPLOYEES;

--GROUP BY
--POR DEPARTAMENTO
SELECT 	D.DEPARTMENT_ID, D.DEPARTMENT_NAME, COUNT(*), 
		MAX(SALARY), TRUNC(AVG(SALARY)), 
		MAX(HIRE_DATE)
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME;

--POR CIUDAD (MUESTRE TAMBIEN EL NOMBRE DEL PAIS)
SELECT 	L.CITY, C.COUNTRY_NAME, COUNT(*), 
		MAX(SALARY), TRUNC(AVG(SALARY)), 
		MAX(HIRE_DATE)
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L 
ON D.LOCATION_ID = L.LOCATION_ID
INNER JOIN COUNTRIES C
ON L.COUNTRY_ID = C.COUNTRY_ID
GROUP BY L.CITY, C.COUNTRY_NAME;

--POR CIUDAD, EXCLUYENDO A LOS EMPLEADOS QUE GANAN MAS DE 15000
SELECT 	L.CITY, C.COUNTRY_NAME, COUNT(*), 
		MAX(SALARY), TRUNC(AVG(SALARY)), 
		MAX(HIRE_DATE)
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L 
ON D.LOCATION_ID = L.LOCATION_ID
INNER JOIN COUNTRIES C
ON L.COUNTRY_ID = C.COUNTRY_ID
WHERE E.SALARY <= 15000
GROUP BY L.CITY, C.COUNTRY_NAME;

--POR CIUDAD, EXCLUYENDO A LAS CIUDADES QUE TENGAN MENOS DE 3 EMPLEADOS
SELECT 	L.CITY, C.COUNTRY_NAME, COUNT(*), 
		MAX(SALARY), TRUNC(AVG(SALARY)), 
		MAX(HIRE_DATE)
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L 
ON D.LOCATION_ID = L.LOCATION_ID
INNER JOIN COUNTRIES C
ON L.COUNTRY_ID = C.COUNTRY_ID
GROUP BY L.CITY, C.COUNTRY_NAME
HAVING COUNT(*) >= 3
ORDER BY COUNT(*) DESC;

--SUBCONSULTAS
--************

--EMPLEADOS QUE GANAN MAS QUE EL PROMEDIO DE LA EMPRESA
SELECT *
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

--EMPLEADOS QUE GANAN MAS QUE EL PROMEDIO DE SU DEPARTAMENTO
SELECT *
FROM EMPLOYEES E
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = E.DEPARTMENT_ID);

--EMPLEADOS QUE PERTENEZCAN A LOS DEPARTAMENTOS CON MAS DE 4 TRABAJADORES
SELECT * 
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN ( SELECT DEPARTMENT_ID
						 FROM EMPLOYEES
						 GROUP BY DEPARTMENT_ID
						 HAVING COUNT(*) > 4);


--MUESTRE EL NOMBRE COMPLETO, SALARIO DEL EMPLEADO Y LA CANTIDAD DE EMPLEADOS EN EL
--DEPARTAMENTO AL QUE PERTENECE

SELECT 	E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME,
		E.SALARY, E.DEPARTMENT_ID,
		(SELECT COUNT(*) FROM EMPLOYEES WHERE DEPARTMENT_ID = E.DEPARTMENT_ID) AS COUNT_DPT
FROM EMPLOYEES E;

--MUESTRE EL NOMBRE COMPLETO DEL EMPLEADO, SU SALARIO, EL NOMBRE DE SU ROL, EL SALARIO MAXIMO
--DE SU DEPARTAMENTO, EL SALARIO MINIMO DE SU DEPARTAMENTO Y EL PROMEDIO DE SALARIOS DE SU
--DEPARTAMENTO. CONSIDERE SOLAMENTE A EMPLEADOS QUE GANEN MAS QUE EL PROMEDIO DE SU DEPARTAMENTO

SELECT 	E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME,
		E.SALARY,
		J.JOB_TITLE, 
		SAL_STATS.MAX_SAL, 
		SAL_STATS.MIN_SAL, 
		SAL_STATS.AVG_SAL
FROM EMPLOYEES E
INNER JOIN JOBS J
ON E.JOB_ID = J.JOB_ID
INNER JOIN (SELECT 	DEPARTMENT_ID, 
					MAX(SALARY) AS MAX_SAL, 
					MIN(SALARY) AS MIN_SAL, 
					TRUNC(AVG(SALARY), 2) AS AVG_SAL
			FROM EMPLOYEES 
			GROUP BY DEPARTMENT_ID) SAL_STATS
ON E.DEPARTMENT_ID = SAL_STATS.DEPARTMENT_ID
WHERE E.SALARY > SAL_STATS.AVG_SAL;


SELECT 	E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME,
		E.SALARY,
		J.JOB_TITLE, 
		SAL_STATS.MAX_SAL, 
		SAL_STATS.MIN_SAL, 
		SAL_STATS.AVG_SAL
FROM EMPLOYEES E
INNER JOIN JOBS J
ON E.JOB_ID = J.JOB_ID
INNER JOIN (SELECT 	DEPARTMENT_ID, 
					MAX(SALARY) AS MAX_SAL, 
					MIN(SALARY) AS MIN_SAL, 
					TRUNC(AVG(SALARY), 2) AS AVG_SAL
			FROM EMPLOYEES 
			GROUP BY DEPARTMENT_ID) SAL_STATS
ON E.DEPARTMENT_ID = SAL_STATS.DEPARTMENT_ID
WHERE E.SALARY > SAL_STATS.AVG_SAL;


